export const credentials = {
  DB_URI: process.env.DB_URI,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  PLAID_CLIENT_ID: process.env.PLAID_CLIENT_ID,
  PLAID_SECRET_KEY: process.env.PLAID_SECRET_KEY,
  PLAID_ENV: process.env.PLAID_ENV,
  DWOLLA_KEY: process.env.DWOLLA_KEY,
  DWOLLA_SECRET: process.env.DWOLLA_SECRET,
  DWOLLA_BASE_URL: process.env.DWOLLA_BASE_URL,
  DWOLLA_ENVIRONMENT: process.env.DWOLLA_ENVIRONMENT,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  STRIPE_ENVIRONMENT: process.env.STRIPE_ENVIRONMENT,
};
